### ISSUE TITLE
bug with error message using cli

### ISSUE THREAD

**Issue by uriva** [instantdb/instant#496]
```
file:///home/uri/.npm/_npx/2a2cb36dc5f602ce/node_modules/instant-cli/index.js:1098
    console.error(noAppIdErrorMessage);
                  ^

ReferenceError: Cannot access 'noAppIdErrorMessage' before initialization
    at getAppIdWithErrorLogging (file:///home/uri/.npm/_npx/2a2cb36dc5f602ce/node_modules/instant-cli/index.js:1098:19)
    at pushSchema (file:///home/uri/.npm/_npx/2a2cb36dc5f602ce/node_modules/instant-cli/index.js:584:23)
    at Command.<anonymous> (file:///home/uri/.npm/_npx/2a2cb36dc5f602ce/node_modules/instant-cli/index.js:72:5)
    at Command.listener [as _actionHandler] (/home/uri/.npm/_npx/2a2cb36dc5f602ce/node_modules/commander/lib/command.js:542:17)
    at /home/uri/.npm/_npx/2a2cb36dc5f602ce/node_modules/commander/lib/command.js:1502:14
    at Command._chainOrCall (/home/uri/.npm/_npx/2a2cb36dc5f602ce/node_modules/commander/lib/command.js:1386:12)
    at Command._parseCommand (/home/uri/.npm/_npx/2a2cb36dc5f602ce/node_modules/commander/lib/command.js:1501:27)
    at /home/uri/.npm/_npx/2a2cb36dc5f602ce/node_modules/commander/lib/command.js:1265:27
    at Command._chainOrCall (/home/uri/.npm/_npx/2a2cb36dc5f602ce/node_modules/commander/lib/command.js:1386:12)
    at Command._dispatchSubcommand (/home/uri/.npm/_npx/2a2cb36dc5f602ce/node_modules/commander/lib/command.js:1261:25)

Node.js v22.7.0
```

**Comment by stopachka** [comment]
Fixed in 0.15.4 with #502 ! Thank you @uriva
